name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [I210, generic, IntelCE]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake doxygen graphviz cppcheck clang-tidy

    - name: Build project
      run: |
        mkdir -p linux
        cd linux
        if [ "${{ matrix.arch }}" == "generic" ]; then
          make clean all
        else
          ARCH=${{ matrix.arch }} make clean all
        fi

    - name: Run static code analysis
      run: |
        cd linux
        make static-analysis

    - name: Run resource management checks
      run: |
        cd linux
        make resource-checks

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64, x86]

    env:
      WPCAP_DIR: ${{ secrets.WPCAP_DIR }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        choco install cmake --version=3.2.2
        choco install visualstudio2013community
        choco install winpcap
        choco install cppcheck
        choco install llvm
        choco install iphlpapi

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        msbuild /p:Configuration=Release

    - name: Run static code analysis
      run: |
        cppcheck .
        clang-tidy .

    - name: Run resource management checks
      run: |
        # Use Visual Studio's built-in tools for resource management checks
        echo "Running resource management checks using Visual Studio's built-in tools"
