name: Sync with Original Repository

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout forked repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Add original repository as remote
      run: |
        git remote add upstream https://github.com/Avnu/gptp.git
        git fetch upstream

    - name: Merge changes from original repository
      run: |
        git checkout main
        git pull upstream main

    - name: Print result of git pull
      run: |
        git log -1
